baseurl = "https://blog.hackervaillant.eu/"
title = "gfeun"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Glenn Feunteun"
    description = "Personal Website"
    keywords = "blog,developer,personal"
    info = "Research Engineer on Content Delivery Networks"
    avatarurl = "images/gfeun.jpeg"
    #footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/gfeun/blog"

    rtl = false

    # Use inverted colors
    colorscheme = "dark"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

    [[params.social]]
        name = "Github"
        icon = "fab fa-github"
        weight = 1
        url = "https://github.com/gfeun/"
    [[params.social]]
        name = "LinkedIn"
        icon = "fab fa-linkedin"
        weight = 2
        url = "https://www.linkedin.com/in/glenn-feunteun/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"


[languages]
    [languages.en]
        languagename = "English"
        [languages.en.menu]
            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"
