---
- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: copy nginx config
  ansible.builtin.copy:
    src: nginx/
    dest: /etc/nginx

- name: generate DH parameters
  community.crypto.openssl_dhparam:
    path: /etc/nginx/dhparam.pem
    size: 2048

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: remove default nginx site
  file:
    path: /etc/nginx/site-enabled/default
    state: absent
