---
- hosts: all
  tasks:
    - name: create certificate directory
      file:
        path: /etc/nginx/ssl/
        state: directory
        mode: '0700'

    - name: copy certificate from environment variable
      copy:
        content: "{{ lookup('env','CERTIFICATE') }}"
        dest: "/etc/nginx/ssl/{{ blog_fqdn }}.crt"

    - name: copy private key from environment variable
      copy:
        content: "{{ lookup('env','PRIVATE_KEY') }}"
        dest: "/etc/nginx/ssl/{{ blog_fqdn }}.key"

    - name: include nginx role
      include_role:
        name: nginx

    - name: copy blog
      copy:
        src: public
        dest: "/var/www/{{ blog_fqdn }}/"
