---
- hosts: all
  tags:
    - install
  tasks:
    - name: copy ovh api credentials
      ansible.builtin.copy:
        src: certbot_ovh.ini
        dest: /etc/letsencrypt/certbot_ovh.ini
        owner: root
        mode: 0600

    - name: include ovh-dyndns role
      ansible.builtin.include_role:
        name: ovh-dyndns

    - name: install certbot
      ansible.builtin.package:
        name:
          - certbot
          - python3-certbot-dns-ovh
        state: present

    - name: run certbot
      ansible.builtin.command: certbot certonly --dns-ovh --dns-ovh-credentials /etc/letsencrypt/certbot_ovh.ini -m "{{ mail_address }}" -d "{{ blog_fqdn }}" --agree-tos --non-interactive

    - name: include nginx role
      ansible.builtin.include_role:
        name: nginx

    - name: install rsync
      ansible.builtin.package:
        name: rsync
        state: present

- hosts: all
  gather_facts: no
  tasks:
    - name: copy blog
      ansible.posix.synchronize:
        src: public
        dest: "/var/www/{{ blog_fqdn }}/"
      tags:
        - blog
